parser: babel-eslint
settings:
  pragma: React
  version: 16.13.1
  # linkComponents:
  # - Hyperlink
  # - name: Link
  #   linkAttribute: to
globals:
  process: true
  window: true
env:
  browser: true
  jest: true
  es6: true
plugins:
  - import
extends:
  - eslint:recommended
  - airbnb
  - plugin:react/recommended
  - plugin:react-hooks/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-param-reassign: off
  no-console: off
  no-continue: off
  no-eval: error
  import/first: error
  react/prop-types: 'off'
  react/jsx-filename-extension: 'off'
  arrow-parens: off
  react/jsx-props-no-spreading: off
  react/display-name: off
  camelcase: off
  no-underscore-dangle: off
  import/no-unresolved: off
  import/prefer-default-export: off
  jsx-a11y/no-static-element-interactions: warn
  jsx-a11y/click-events-have-key-events: warn
  react-hooks/exhaustive-deps: error
  max-len: ["error", 120, 2]