version: "3"

services:
  app:
    image: fabalexsie/your_spotify_server
    restart: unless-stopped
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      API_ENDPOINT: http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: http://localhost:3000
      SPOTIFY_PUBLIC: __your_spotify_client_id__
      SPOTIFY_SECRET: __your_spotify_secret__

  mongo:
    image: mongo:6
    restart: unless-stopped
    logging:
      driver: none
    volumes:
      - your_spotify_db:/data/db
    ports:
      - "27017:27017"

  web:
    image: fabalexsie/your_spotify_client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      API_ENDPOINT: http://localhost:8080

volumes:
  your_spotify_db:
    external: true
