version: "3"

services:
  app:
    container_name: your-spotify-server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    entrypoint: "/app/scripts/run/run_dev.sh"
    volumes:
      - ./server/src/:/app/src/
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      API_ENDPOINT: http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: http://localhost:3000
      SPOTIFY_PUBLIC: __your_spotify_client_id__
      SPOTIFY_SECRET: __your_spotify_secret__
      LOG_LEVEL: debug

  mongo:
    image: mongo:6
    restart: always
    logging:
      driver: none
    volumes:
      - your_spotify_db:/data/db
    ports:
      - "27017:27017"

  web:
    container_name: your-spotify-web
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    entrypoint: "/app/scripts/run/run_dev.sh"
    volumes:
      - ./client/src:/app/src/
      - ./client/public:/app/public/
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      API_ENDPOINT: http://localhost:8080

volumes:
  your_spotify_db:
    external: true
