version: "3"

services:
  app:
    container_name: express-mongo
    restart: always
    build:
     context: ./server
     dockerfile: Dockerfile.production
     args:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://localhost:3000
      - SPOTIFY_PUBLIC=__your_spotify_client_id__
      - SPOTIFY_SECRET=__your_spotify_secret__
      - CORS=http://localhost:3000,http://localhost:3001
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify

  mongo:
    container_name: mongo
    image: mongo:4.4.8

  web:
    container_name: web
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.production
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://localhost:8080
