packages:
  - apps/*

catalog:
  '@eslint/css': 0.14.1
  '@eslint/js': 9.39.2
  '@eslint/json': 0.14.0
  '@rsbuild/core': 1.6.15
  eslint: 9.39.2
  eslint-plugin-unused-imports: 4.3.0
  globals: 16.5.0
  typescript: 5.9.3
  typescript-eslint: 8.50.1

onlyBuiltDependencies:
  - core-js
  - unrs-resolver
