parser: "@babel/eslint-parser"
env:
  commonjs: true
  es6: true
  node: true
extends: 'airbnb', "@babel"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  no-underscore-dangle: off,
  no-param-reassign: off,
  arrow-parens: off,
  linebreak-style: off,
  no-await-in-loop: off,
  no-continue: off,
}
