FROM node:16-alpine AS builder

WORKDIR /app

RUN apk add python3 gcc g++ make cmake

COPY tsconfig.json /app/tsconfig.json
COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock

RUN yarn install --frozen-lockfile

COPY src/ /app/src/
COPY scripts/ /app/scripts/

RUN yarn build

ENTRYPOINT [ "sh", "/app/scripts/run/run.sh" ]